### ISSUE TITLE
Refresh token before expiry

### ISSUE THREAD

**Issue by cstenglein** [cstenglein/raspiblitz-web#146]
Call `/system/refresh-token` before expiry if the user makes a action (e.g. mouse click / move) so the token doesn't run out when doing something.

**Comment by escapedcat** [comment]
Do we need a time-out logout right now?  
Asking because we could also just get a new token every i.e. 2 minutes. If the users wants to logout they can do that.  

If we later on need it on interaction because we want to logout the user automatically after i.e. 5 minutes of inactivity we could add that later with another ticket.

**Comment by cstenglein** [comment]
Yeah could be also a solution to check for expiry of the token and then refresh e.g. every 30s before expiry.

**Comment by cstenglein** [comment]
/system/refresh-token is the endpoint for this.
