### ISSUE TITLE
Build Skeleton for Setup

### ISSUE THREAD

**Issue by cstenglein** [cstenglein/raspiblitz-web#217]
Build The skeleton for the setup

![image](https://user-images.githubusercontent.com/9399034/157751316-4afb8b88-c9ef-4e9b-9b48-470b0d1a24ef.png)

**Comment by rootzoll** [comment]
At the moment its a bit hard to put the setup into fixed steps because it depends what mode you run it in and also for the v1.8 the WebUI setup will not have all possible setup options (like uploading migration or rescue files) in it. So recommend to revisit this for a v1.8.1 release of RaspiBlitz and go just with a simplified view on the setup for v1.8.

**Comment by cstenglein** [comment]
Current Skeleton is enough => closed.

Will add another issue for a nicer design later on.
