### ISSUE TITLE
replace variables with tailwind classes to css classes with @apply

### ISSUE THREAD

**Issue by cstenglein** [cstenglein/raspiblitz-web#43]
It was faster to compile.
Now that the design won't be redone much until the first release, change the variables to css classes and apply the tailwind classes to it.

**Comment by cstenglein** [comment]
Not sure if it really is better to use @apply, need to come back later to it

**Comment by escapedcat** [comment]
Talked to a friend who is more familiar with this. He said no need to use apply if you mostly use styles in jsx-components.  

But things could be improved i.e. use `items.maps()` here instead of repeating markup:
https://github.com/cstenglein/raspiblitz-web/blob/master/src/components/Navigation/SideDrawer/SideDrawer.tsx#L24
