### ISSUE TITLE
Rc2 issues

### ISSUE THREAD

**Issue by cstenglein** [cstenglein/raspiblitz-web#567]
- final setup after Recovery 401 issue

**Comment by fusion44** [comment]
Something which can be a quick fix is that the SendModal still uses `pay_request.num_satoshis`, which is deprecated. It should use `num_msat` instead. [source](https://github.com/cstenglein/raspiblitz-web/blob/025788eee509dac8cf8308d34dfc5fc1e187108d/src/pages/Home/SendModal/SendModal.tsx#L41)

Problem is that `num_satoshis` discards the floating point value and thus returns 66 sat instead of 66444 millisat. I'd like to focus on msat when dealing with lightning via the API.

**Comment by cstenglein** [comment]
Thank you @fusion44, changed the field in #573
