### ISSUE TITLE
wrong icon on btc rpc explorer

### ISSUE THREAD

**Issue by nyxnor** [cstenglein/raspiblitz-web#60]
it is using the Sphinx Chat icon, not the BTC RPC Explorer

https://github.com/cstenglein/raspiblitz-web/blob/master/images/2021-09-15/appdetails_dark.png

![image](https://user-images.githubusercontent.com/69700936/135855533-6c84f323-2aee-4e45-844d-1f2b03e4d877.png)

**Comment by bitpaint** [comment]
I don't have this issue on my side... 
[image](https://user-images.githubusercontent.com/67663265/135939686-cbcbfe14-a144-49e6-8778-02af88463a2e.png)

**Comment by cstenglein** [comment]
Thanks for pointing that out @nyxnor !

That is just an issue with the actual application, just with the mock-backend since i'm sending static data there:

https://github.com/cstenglein/raspiblitz-web/blob/master/backend-mock/apps.js#L136-L154

So when using the mock-backend and clicking on "details" on any app, it opens the info about BTC RPC Explorer but keeps the icon you clicked "details" on. 

Just tested with mock-backend again, don't worry :)
